# GitHub Actions build workflow
name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies - macOS
        run: |
          echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
          echo "PYTORCH_MPS_DISABLE=1" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Install dependencies - Windows
        run: |
          "PYTHONIOENCODING=utf-8" >> $env:GITHUB_ENV
          choco install wget
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          pip install -U wheel coverage coveralls
          pip install .
          python --version
          make data coverage

      - uses: pre-commit/action@v3.0.0
        if: matrix.os == 'ubuntu-latest'

      - name: Test Coverage
        run: coveralls --service=github
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
