# GitHub Actions build workflow
name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies - macOS
        run: |
          brew install libomp
          pip install torch==1.12.1 torchvision==0.13.1
        if: matrix.os == 'macos-latest'

      - name: Install dependencies - Windows
        run: choco install wget
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          pip install -U pip
          pip install -U wheel coverage coveralls
          pip install .
          python -c "import nltk; nltk.download('punkt')"
          python --version
          make data coverage
        env:
          PYTHONUTF8: 1

      - uses: pre-commit/action@v3.0.0
        if: matrix.os == 'ubuntu-latest'

      - name: Test Coverage
        run: coveralls --service=github
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}