# GitHub Actions build workflow
name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies - Windows
        run: choco install wget
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          pip install -U wheel coverage coveralls
          pip install . fasttext==0.9.2
          python --version
          make data coverage
        env:
          PYTHONUTF8: 1

      - uses: pre-commit/action@v3.0.0
        if: matrix.os == 'ubuntu-latest'

      - name: Test Coverage
        run: coveralls --service=github
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
